from pydantic import BaseModel, Field, model_validator
from typing import Optional, Dict, Any, List
from uuid import UUID
from datetime import datetime

from app.core.tenant_paths import validate_job_storage_paths


class PipelineDefinition(BaseModel):
    nodes: List[Dict[str, Any]] = Field(..., description="List of nodes in the graph")
    edges: List[Dict[str, Any]] = Field(
        ..., description="List of directed edges in the graph"
    )


class JobSubmitRequest(BaseModel):
    tenant_id: UUID = Field(..., description="Tenant boundary for S3 key validation")
    external_execution_id: UUID = Field(
        ..., description="Unique run identifier from mipc"
    )
    pipeline: PipelineDefinition = Field(..., description="The DAG pipeline topology")
    inputs: Dict[str, Any] = Field(
        ..., description="Inputs mapping source nodes to storage configurations"
    )
    output: Dict[str, Any] = Field(
        ..., description="Destination S3 key/bucket configurations"
    )
    callback_url: Optional[str] = Field(
        None, description="Optional callback URL for status reports"
    )

    @model_validator(mode="after")
    def validate_storage_boundaries(self) -> "JobSubmitRequest":
        validate_job_storage_paths(str(self.tenant_id), self.inputs, self.output)

        return self


class JobSubmitResponse(BaseModel):
    job_id: str = Field(
        ..., description="Unique execution task job identifier generated by Celery"
    )
    status: str = Field(..., description="Job status, e.g. 'queued'")
    submitted_at: datetime = Field(
        ..., description="Timestamp of when the job was accepted"
    )


class JobStatusResponse(BaseModel):
    job_id: str = Field(..., description="Job execution identifier")
    tenant_id: UUID = Field(..., description="Tenant boundary for the job")
    external_execution_id: UUID = Field(
        ..., description="Unique run identifier from mipc"
    )
    status: str = Field(
        ..., description="Status string: queued, running, completed, failed, cancelled"
    )
    progress: float = Field(0.0, description="Percentage completion from 0.0 to 100.0")
    current_node: Optional[str] = Field(
        None, description="Active processor node ID executing"
    )
    started_at: Optional[datetime] = Field(None, description="Timestamp of task start")
    finished_at: Optional[datetime] = Field(
        None, description="Timestamp of task completion"
    )
    outputs: Dict[str, Any] = Field(
        default_factory=dict, description="Output file metadata mappings"
    )
    error: Optional[Any] = Field(
        None, description="Error payload details if task failed"
    )


class JobCancelResponse(BaseModel):
    job_id: str = Field(..., description="Cancelled job execution identifier")
    status: str = Field(..., description="Result status, e.g. 'cancelled'")
    cancelled_at: datetime = Field(
        ..., description="Timestamp of cancellation request completion"
    )
