from pydantic import BaseModel, ConfigDict, Field, model_validator
from typing import Optional, Dict, Any, List
from uuid import UUID
from datetime import datetime

from app.core.tenant_paths import validate_job_storage_paths


class PipelineDefinition(BaseModel):
    """Directed Acyclic Graph topology for image processing."""

    nodes: List[Dict[str, Any]] = Field(..., description="List of nodes in the graph")
    edges: List[Dict[str, Any]] = Field(
        ...,
        description=("List of directed edges in the graph"),
    )


class JobSubmitRequest(BaseModel):
    """Request payload to queue an image-processing job."""

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "tenant_id": ("a1b2c3d4-e5f6-" "7890-abcd-ef1234567890"),
                    "external_execution_id": (
                        "f0e1d2c3-b4a5-" "9687-fedc-ba0987654321"
                    ),
                    "pipeline": {
                        "nodes": [
                            {
                                "id": "n1",
                                "type": "input",
                                "parameters": {},
                            },
                            {
                                "id": "n2",
                                "type": "gaussian_blur",
                                "parameters": {
                                    "kernel_size": 5,
                                    "sigma": 1.0,
                                },
                            },
                            {
                                "id": "n3",
                                "type": "output",
                                "parameters": {},
                            },
                        ],
                        "edges": [
                            {
                                "source": "n1",
                                "source_handle": ("output_image"),
                                "target": "n2",
                                "target_handle": ("input_image"),
                            },
                            {
                                "source": "n2",
                                "source_handle": ("output_image"),
                                "target": "n3",
                                "target_handle": ("input_image"),
                            },
                        ],
                    },
                    "inputs": {
                        "n1": {
                            "key": (
                                "a1b2c3d4-e5f6-"
                                "7890-abcd-"
                                "ef1234567890/"
                                "uploads/photo.png"
                            )
                        }
                    },
                    "output": {
                        "prefix": (
                            "a1b2c3d4-e5f6-" "7890-abcd-" "ef1234567890/results/"
                        )
                    },
                    "callback_url": (
                        "https://mipc.example.com" "/api/v1/callbacks/jobs"
                    ),
                }
            ]
        }
    )

    tenant_id: UUID = Field(
        ...,
        description=("Tenant boundary for S3 key validation"),
    )
    external_execution_id: UUID = Field(
        ...,
        description="Unique run identifier from mipc",
    )
    pipeline: PipelineDefinition = Field(..., description="The DAG pipeline topology")
    inputs: Dict[str, Any] = Field(
        ...,
        description=("Inputs mapping source nodes " "to storage configurations"),
    )
    output: Dict[str, Any] = Field(
        ...,
        description=("Destination S3 key/bucket configurations"),
    )
    callback_url: Optional[str] = Field(
        None,
        description=("Optional callback URL for status reports"),
    )

    @model_validator(mode="after")
    def validate_storage_boundaries(
        self,
    ) -> "JobSubmitRequest":
        validate_job_storage_paths(str(self.tenant_id), self.inputs, self.output)

        return self


class JobSubmitResponse(BaseModel):
    """Confirmation of a queued processing job."""

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "job_id": ("c8a7b6d5-e4f3-" "2190-abcd-ef9876543210"),
                    "status": "queued",
                    "submitted_at": ("2026-06-12T10:30:00Z"),
                }
            ]
        }
    )

    job_id: str = Field(
        ...,
        description=("Unique execution task job identifier " "generated by Celery"),
    )
    status: str = Field(..., description="Job status, e.g. 'queued'")
    submitted_at: datetime = Field(
        ...,
        description=("Timestamp of when the job was accepted"),
    )


class JobStatusResponse(BaseModel):
    """Full status snapshot of a processing job."""

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "job_id": ("c8a7b6d5-e4f3-" "2190-abcd-ef9876543210"),
                    "tenant_id": ("a1b2c3d4-e5f6-" "7890-abcd-ef1234567890"),
                    "external_execution_id": (
                        "f0e1d2c3-b4a5-" "9687-fedc-ba0987654321"
                    ),
                    "status": "running",
                    "progress": 45.0,
                    "current_node": "gaussian_blur",
                    "started_at": ("2026-06-12T10:30:05Z"),
                    "finished_at": None,
                    "outputs": {},
                    "error": None,
                }
            ]
        }
    )

    job_id: str = Field(..., description="Job execution identifier")
    tenant_id: UUID = Field(
        ...,
        description="Tenant boundary for the job",
    )
    external_execution_id: UUID = Field(
        ...,
        description="Unique run identifier from mipc",
    )
    status: str = Field(
        ...,
        description=("Status string: queued, running, " "completed, failed, cancelled"),
    )
    progress: float = Field(
        0.0,
        description=("Percentage completion from 0.0 to 100.0"),
    )
    current_node: Optional[str] = Field(
        None,
        description=("Active processor node ID executing"),
    )
    started_at: Optional[datetime] = Field(None, description="Timestamp of task start")
    submitted_at: Optional[datetime] = Field(
        None,
        description="Timestamp of when the job was accepted",
    )
    finished_at: Optional[datetime] = Field(
        None,
        description="Timestamp of task completion",
    )
    outputs: Dict[str, Any] = Field(
        default_factory=dict,
        description="Output file metadata mappings",
    )
    error: Optional[Any] = Field(
        None,
        description=("Error payload details if task failed"),
    )


class JobCancelResponse(BaseModel):
    """Result of a job cancellation request."""

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "job_id": ("c8a7b6d5-e4f3-" "2190-abcd-ef9876543210"),
                    "status": "cancelled",
                    "cancelled_at": ("2026-06-12T10:32:15Z"),
                }
            ]
        }
    )

    job_id: str = Field(
        ...,
        description=("Cancelled job execution identifier"),
    )
    status: str = Field(
        ...,
        description=("Result status, e.g. 'cancelled'"),
    )
    cancelled_at: datetime = Field(
        ...,
        description=("Timestamp of cancellation " "request completion"),
    )
